extern void i2c_usb_pd_stusb4500_print_alert_status1(union stusb4500_alert_status1_t *alert_status1);
extern void i2c_usb_pd_stusb4500_print_port_status(union stusb4500_port_status_t *port_status);



extern void i2c_usb_pd_stusb4500_print_pdo_structure(union stusb4500_pdo_t *pdo);
extern void i2c_usb_pd_stusb4500_print_usb_pd_status(union stusb4500_usb_pd_status_t *usb_pd_status);
extern void i2c_usb_pd_stusb4500_print_fixed_supply_pdo_source_t(union stusb4500_fixed_supply_pdo_source_t *pdo);
extern void i2c_usb_pd_stusb4500_print_variable_supply_pdo_source_t(union stusb4500_variable_supply_pdo_source_t *pdo);
extern void i2c_usb_pd_stusb4500_print_battery_supply_pdo_source_t(union stusb4500_battery_supply_pdo_source_t *pdo);
extern void i2c_usb_pd_stusb4500_print_rx_data_structure(union stusb4500_rx_data_t *rx_data);
