#define TASK_STACK_SIZE 1024

#define GPIO_BUTTON1_PORT  GPIO1
#define GPIO_BUTTON1_PIN   0U
#define GPIO_BUTTON2_PORT  GPIO1
#define GPIO_BUTTON2_PIN   1U
#define GPIO_BUTTON3_PORT  GPIO1
#define GPIO_BUTTON3_PIN   3U
#define GPIO_BUTTON4_PORT  GPIO1
#define GPIO_BUTTON4_PIN   5U

#define master_task_PRIORITY (configMAX_PRIORITIES - 2)
